apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: getenv1
#   namespace: argo-rollouts 
spec:
  args:
  - name: template-arg-key
    value: template-arg-value
  - name: rollout-arg-key
  dryRun:
  - metricName: getenv
  metrics:
  - name: getenv
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: getenv1
                image: alpine
                command: ["sh","-c","env && sleep 20"]
                env:
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: phase
                  value: Successful
                - name: ARG_ROLLOUT_KEY
                  value: "{{args.rollout-arg-key}}"          
              restartPolicy: Never
          backoffLimit: 2
