apiVersion: v1
kind: ConfigMap
metadata:
  name: analysis-temp-opsmx
data:
  providerConfig: |
    application: opsmx-job-ta
    user: admin
    opsmxIsdUrl: 'https://isd-dev.argo-dev.opsmx.net/'
    lifetimeMinutes: 3
    intervalTime: 3
    lookBackType: sliding
    gitops: true
    passScore: 90
    serviceList:
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "argocd,{{env.STABLE_POD_HASH}},demoapp-issuegen"
      canaryMetricScope: "argocd,{{env.LATEST_POD_HASH}},demoapp-issuegen"
      metricTemplateName: "metricym"


