apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: job-analysis-new
spec:
  args:
    - name: baseline-hash
    - name: preview-hash
  metrics:
    - name: job-analysis-new
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: svc-acc
                imagePullSecrets:
                - name: opsmx11-secret
                containers:
                - name: job-analysis-new
                  image: opsmx11/argo-isd-metric-provider-job:v1.1.22
#                   image: shraddhaopsmx/test-code:v1.2.3
                  imagePullPolicy: Always
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.preview-hash}}"
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: gitopstemplates
                      mountPath: /etc/config/templates
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: analysis-temp-opsmx
                - name: gitopstemplates
                  projected:
                    sources:
                    - configMap:
                        name: metricym
                    - configMap:
                        name: log-yaml             
                - name: secret-config-volume
                  secret:
                    secretName: opsmxprofile-123
                    optional: false
