apiVersion: v1
kind: ConfigMap
metadata:
  name: log-yaml
data:
  log-yaml-data: |
    monitoringProvider: ELASTICSEARCH
    accountName: logEalastic1
    scoringAlgorithm: Autonomous Scoring
    index: kubernetes*
    responseKeywords: log
    autoBaseline: true
    errorTopics:
    - errorString: OnOutOfMemoryError
      topic: CRITICAL
      type: NotSodefault
