apiVersion: v1
kind: ConfigMap
metadata:
  name: log-yaml
data:
  log-yaml-data: |
    monitoringProvider: ELASTICSEARCH
    accountName: logEalastic1
    scoringAlgorithm: Canary
    index: kubernetes*
    responseKeywords: log
    autoBaseline: false
    errorTopics:
    - errorString: OnOutOfMemoryError
      topic: CRITICAL
      type: NotSodefault
