---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
   - "batch"
  resources:
   - jobs/status
  verbs:
   - get
   - list
   - patch
- apiGroups:	
   - ""	
  resources:	
   - pods	
  verbs:	
   - get	
   - list
- apiGroups:
  - datasource.analytics.opsmx.com/v1alpha1
  resources:
  - dscrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datasource.analytics.opsmx.com/v1alpha1
  resources:
  - dscrds/finalizers
  verbs:
  - update
- apiGroups:
  - datasource.analytics.opsmx.com/v1alpha1
  resources:
  - dscrds/status
  verbs:
  - get
  - patch
  - update  
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
