---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: "opsmx.com:datasource:reader"
rules:
    - apiGroups: ['*']
      resources: ['*']
      verbs: ['*']
    - apiGroups: ["opsmx.com"]
      resources: ["datasources"]
      verbs: ["get", "list", "watch", "create", "patch", "delete", "update", "watch"]
    - apiGroups: ["opsmx.com"]
      resources: ["datasources/finalizers"]
      verbs: ["update"]
    - apiGroups: ["opsmx.com"]
      resources: ["datasources/status"]
      verbs: ["get", "patch", "update"]
    - apiGroups: ["batch"]
      resources: ["jobs/status"]
      verbs: ["get", "list", "patch"]
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: "opsmx.com:datasource:dscdreader-read"
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: "opsmx.com:datasource:reader"
subjects:
    - kind: ServiceAccount
      name: dscrdreader
      namespace: argocd
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: dscrdreader
