apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
spec:
  generators:
  - list:
      elements:
        - appName: app-from-appset
          namespace: argocd
          url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/shraddhaopsmx/argotest.git
        targetRevision: HEAD
        path: "appset-test/{{appName}}"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
          valueFiles:
          - "../{{appName}}/values.yaml"
          values: "server: {{url}}"
      destination:
        server: "{{url}}"
        namespace: "{{namespace}}"
      # syncPolicy:
      #   automated:
      #     prune: true
      #     selfHeal: true
        syncOptions:
          - CreateNamespace=true
