apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config-ss-false
data:
  providerConfig: |
    application: elkgitopsfalse-ss-false
    baselineStartTime: "2022-12-08T22:10:29.000Z"
    canaryStartTime: "2022-12-08T22:10:29.000Z"
    lifetimeMinutes: 6
    gitops: false
    passScore: 90
    serviceList: 
    - logTemplateName: logtemplateelkdec16
      logTemplateVersion: v1.0
      logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: "sapor-gate-bb6b9fbcf-lj6bl"
      canaryLogScope: "sapor-gate-bb6b9fbcf-lj6bl"
      service: elk-service01
