apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: dashboard-apps
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/templates/dashtemp
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
