apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: opsmx-ta
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
    - name: test-secret-sub
      valueFrom:
        secretKeyRef:
          name: isd-demo-cd-profile
          key: opsmxIsdUrl
  metrics:
    - name: opsmx-ta
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: opsmx-ta
                imagePullSecrets:
                - name: opsmx11-secret
                containers:
                - name: opsmx-ta
                  image: opsmx11/argo-isd-metric-provider-job:v1.1.22
                  imagePullPolicy: Always
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.canary-hash}}"
                    - name: SECRET_SUB
                      value: "{{args.test-secret-sub}}"
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: gitopstemplates
                      mountPath: /etc/config/templates
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: analysis-temp-ta
                - name: gitopstemplates
                  projected:
                    sources:
                    - configMap:
                        name: elastic
                - name: secret-config-volume
                  secret:
                    secretName: opsmx-prof
                    optional: false   
