apiVersion: v1
kind: Secret
metadata:
  name: opsmx-prof
type: Opaque
data:
  cdIntegration: dHJ1ZQ==
  sourceName: YXJnb2NkNg==
  opsmxIsdUrl: aHR0cHM6Ly9pc2QtZGV2LmFyZ28tZGV2Lm9wc214Lm5ldA==
  user: dXNlcjI=
