apiVersion: apps/v1
kind: Deployment
metadata:
  name: scout-demo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scout-demo-service
  template:
    metadata:
      labels:
        app: scout-demo-service
    spec:
      containers:
        - image: docker.io/opsmx11/scout-demo-service:3be42d8ba-5
          name: scout-demo-service
