apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pure-gitops-analysisjk
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: pure-gitops-analysisjk
      initialDelay: 20s
      provider:
        plugin:
          opsmx: |
           {
           "address" : "https://isd-dev.argo-dev.opsmx.net/"
           }
