apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pure-gitops-analysisjk
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
  - name: pure-gitops-analysisjk
    count: 1
    initialDelay: 20s
    provider:
      plugin:
        argoproj-labs/rollouts-opsmx-metric-plugin:
#           application: app23m2
          lifetimeMinutes: 3
          intervalTime: 3
          gitops: true
          profile: opsmx-profile-ss
          passScore: 90
          marginalScore: 65
          globalLogTemplate: logtemp
          serviceList: 
          - metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "oes,.*{{args.baseline-hash}}.*"
            canaryMetricScope: "oes,.*{{args.canary-hash}}.*"
            metricTemplateName: "metricyml"
            serviceName: "metriconly"
          - logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: "{{args.baseline-hash}}"
            canaryLogScope: "{{args.canary-hash}}"
            logTemplateName: "logyml-ss"  
