apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pure-gitops-analysisjk
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
  - name: pure-gitops-analysisjk
    count: 1
    initialDelay: 20s
    provider:
      plugin:
        opsmx:
          application: test-plugin
          lifetimeMinutes: 3
          intervalTime: 3
          gitops: true
          profile: opsmx-profile-ss
          passScore: 90
          marginalScore: 65
          globalLogTemplate: logtemp
          serviceList: 
          - metricScopeVariables: "${app_name},${pod_key}"
            baselineMetricScope: "oes,.*{{args.baseline-hash}}.*"
            canaryMetricScope: "oes,.*{{args.canary-hash}}.*"
            metricTemplateName: "promTemp0702"
            serviceName: "metriconly"
          - metricScopeVariables: "${app_name},${pod_key}"
            baselineMetricScope: "oes,{{args.baseline-hash}}"
            canaryMetricScope: "oes,{{args.canary-hash}}"
            metricTemplateName: "promTemp0702"
            logScopeVariables: "kubernetes.pod_name"
            logTemplateName: logyml-ss
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"            
            
