apiVersion: v1
kind: ConfigMap
metadata:
  name: logyml-ss
data:
  logyml-ss2: |
    monitoringProvider: ELASTICSEARCH
    accountName: ds-elastic
    scoringAlgorithm: Canary
    index: kubernetes*
    responseKeywords: log,message
    disableDefaultErrorTopics: true
    tags:
    - errorString: NOnOutOfMemoryError
      tag: NotJunaid
    errorTopics:
    - errorString: OnOutOfMemoryError
      topic: CRITICAL
      type: NotSodefault
