apiVersion: v1
kind: ConfigMap
metadata:
  name: metricym
data:
  metricym: |
    accountName: ds-prometheus
    metricType: ADVANCED
    advancedProvider: PROMETHEUS
    metricTemplateSetup:
      isNormalize: false
      groups:
        - metrics:
            - name: "avg(container_memory_usage_bytes{namespace=\"${namespace_key}\", pod=~\".*${pod_key}.*\"})"
              riskDirection: "higherOrLower"
              criticality: MustHave
          group: "Memory Usage By Pod Name"
        - metrics:
            - name: "avg(rate(container_cpu_usage_seconds_total{namespace=\"${namespace_key}\", pod=~\".*${pod_key}.*\"}[1m]) * 100)"
              riskDirection: higher
          group: CPU Usage By Pod Name
