apiVersion: v1
kind: ConfigMap
metadata:
  name: metricyml
data:
  newrelic: |
    accountName: NewRelicAAQQQAQQAAQ
    metricType: ADVANCED
    metricWeight: 1
    criticality: Normal
    nanStrategy: ReplaceWithZero
    metricTemplateSetup:
      percent_diff_threshold: hard
      isNormalize: false   
      groups:
        - metrics:
            - riskDirection: Higher
              customThresholdHigherPercentage: 60
              name: "SELECT average(duration)*1000 FROM Transaction WHERE appName = '${app_key}' AND host RLIKE '${pod_key}'"
              customThresholdLowerPercentage: 10
          group: "Tx Time"
        - metrics:
            - riskDirection: Higher
              customThresholdHigherPercentage: 60
              name: "SELECT apdex(apm.service.apdex) FROM Metric WHERE appName='${app_key}' AND host RLIKE '${pod_key}'"
              customThresholdLowerPercentage: 10
          group: "Apdex "
        - metrics:
            - riskDirection: Higher
              customThresholdHigherPercentage: 60
              name: "SELECT average(apm.service.transaction.duration)*1000 as responseTime FROM Metric WHERE appName = '${app_key}' AND host RLIKE '${pod_key}'"
              customThresholdLowerPercentage: 10
          group: "Application Transcation"
    advancedProvider: NEWRELIC     
