apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config-ss
data:
  providerConfig: |
    application: opsmx-job-ta
    baselineStartTime: "2021-11-03T11:29:46.915Z"
    canaryStartTime: "2021-11-03T11:29:46.915Z"
    lifetimeMinutes: 3
    gitops: false
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${namespace_key},${pod_key}"
      baselineMetricScope: "pmalpha-prod,7d4845fdc"
      canaryMetricScope: "pmalpha-prod,7d4845fdc"
      metricTemplateName: "metricprom100"
    - logTemplateName: logmultiservice
      logScopeVariables: "kubernetes.container_name"
      baselineLogScope: "baseapp-rest-1"
      canaryLogScope: "canaryapp-rest-1"
      serviceName: "LogAloneSvc"
