apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: rollout-plugin-app
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
  - name: rollout-plugin-app-1
    count: 1
    initialDelay: 20s
    provider:
      plugin:
        argoproj-labs/rollouts-opsmx-metric-plugin:
#           application: app23m2
          lifetimeMinutes: 3
          intervalTime: 3
          gitops: true
          profile: opsmx-profile-ss1
          passScore: 90
          marginalScore: 60
          globalLogTemplate: logtemp
          serviceList: 
          - metricScopeVariables: "${app_name},${namespace_key},${pod_key}"
            baselineMetricScope: "rollout-plugin-app,argocd,.*{{args.baseline-hash}}.*"
            canaryMetricScope: "rollout-plugin-app,argocd,.*{{args.canary-hash}}.*"
            metricTemplateName: "prometheus-app-health"
            serviceName: "metricsonly"
#           - logScopeVariables: "kubernetes.pod_name"
#             baselineLogScope: "{{args.baseline-hash}}"
#             canaryLogScope: "{{args.canary-hash}}"
#             logTemplateName: "logyml-ss"
