apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-log-verifier-sample
data:
  elasticsearch-log-verifier-sample: |
    monitoringProvider: ELASTICSEARCH
    accountName: ds-elastic
    index: kubernetes*
    filterKey: kubernetes.pod_name
    responseKeywords: log
    errorTopics: 
    - errorString: NoClassDefFoundError
      topic: error
    - errorString: OnOutOfMemoryError
      topic: error
