apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    app.kubernetes.io/name: {{ .Release.Name  }}
    component: auditservice
  name: oes-audit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: auditservice
  template:
    metadata:
      labels:
        app: oes
        app.kubernetes.io/name: {{ .Release.Name  }}
        component: auditservice
        ssd.admissionreview.accountname: {{ index (index .Values .Release.Namespace) "account" }}
        ssd.admissionreview.appname: {{ .Release.Name  }}
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx512m
        image: nginx:bookworm
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /mgmt/health
            port: 8097
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: oes-audit-service
        ports:
        - containerPort: 8097
          name: backend
          protocol: TCP
