apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    app.kubernetes.io/name: backend-audit-services-argo
    component: auditservice
  name: oes-audit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: auditservice
  template:
    metadata:
      labels:
        app: oes
        app.kubernetes.io/name: backend-audit-services-argo
        component: auditservice
        ssd.admissionreview.accountname: dev
        ssd.admissionreview.appname: {{ .Release.Name  }}
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx512m
        image: nginx:bookworm
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /mgmt/health
            port: 8097
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: oes-audit-service
        ports:
        - containerPort: 8097
          name: backend
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8097
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opsmx/conf/audit-service-local.yml
          name: audit-config-volume
          subPath: audit-local.yml
        - mountPath: /opsmx/conf/bootstrap.yml
          name: bootstrap-config-volume
          subPath: bootstrap.yml
        - mountPath: /opsmx/conf/standard-error-code.csv
          name: standard-error-conf
          subPath: standard-error-codes.csv
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: opsmx11-secret
      initContainers:
      - command:
        - /bin/bash
        - -c
        - sleep 30;echo Waiting for oes-db to be up and running; pg_isready -h oes-db
          -p 5432 && echo PostgreSQL DB is ready to receive connections
        image: postgres:9.6.5
        imagePullPolicy: IfNotPresent
        name: db-check
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: audit-config-volume
        secret:
          defaultMode: 420
          items:
          - key: audit-local.yml
            path: audit-local.yml
          secretName: oes-audit-service-config
      - name: bootstrap-config-volume
        secret:
          defaultMode: 420
          items:
          - key: bootstrap.yml
            path: bootstrap.yml
          secretName: bootstrap
      - configMap:
          defaultMode: 420
          items:
          - key: standard-error-codes.csv
            path: standard-error-codes.csv
          name: standard-error-codes-config
        name: standard-error-conf
