apiVersion: batch/v1
kind: Job
metadata:
  # generateName: webhook-job-
  name: job123
  # annotations:
  #   argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: webhook-caller
        image: quay.io/opsmxpublic/awsgit:v2-openssh-javalibs
        command: ["/bin/sh", "-c"]
        args:
        - | 
          #Construct payload
          # PAYLOAD="{"\"imageList"\": $IMAGES, "\"account"\": "\"{{ (index .Values .Values.server).account }}"\"}"
          echo payload is $PAYLOAD

          #Send payload to webhook
          # curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" https://ssd-opa.oes.opsmx.org/api/v1/dataCollection

      restartPolicy: Never
  backoffLimit: 1
