apiVersion: batch/v1
kind: Job
metadata:
  # generateName: webhook-job-
  name: job123
  # annotations:
  #   argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: webhook-caller
        image: quay.io/opsmxpublic/awsgit:v2-openssh-javalibs
        command: ["/bin/sh", "-c"]
        args:
        - | 
          PAYLOAD="{"\"imageList"\": "image123", "\"account"\": "\"{{ (index .Values .Values.server).account }}"\"}"
          echo payload is $PAYLOAD
      restartPolicy: Never
  backoffLimit: 1
