apiVersion: v1
kind: Service
metadata:
  name: svc1
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: app-from-appset
    release: app-from-appset
