kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sj-analysis-ta
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: sj-analysis-ta
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          profile: opsmx-profile-v5
          application: final-test-ta
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          user: admin
#           intervalTime: 15
#           lookBackType: growing
          lifetimeMinutes: 5
          threshold:
            pass: 90
            marginal: 65
          globalMetricTemplate: prometheusverification
          globalLogTemplate: templateLogTemplate
          services:
          - logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
            logTemplateVersion: "v2.0"
          - logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
            logTemplateVersion: "v2.0"
          - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,{{args.baseline-hash}},demoapp-issuegen"
            canaryMetricScope: "argocd,{{args.canary-hash}},demoapp-issuegen"
            metricTemplateName: "PrometheusMetricTemplate" 
          - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,{{args.baseline-hash}},demoapp-issuegen"
            canaryMetricScope: "argocd,{{args.canary-hash}},demoapp-issuegen"
            metricTemplateName: "PrometheusMetricTemplate" 
            logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
          - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,{{args.baseline-hash}},demoapp-issuegen"
            canaryMetricScope: "argocd,{{args.canary-hash}},demoapp-issuegen"
            metricTemplateName: "PrometheusMetricTemplate" 
          - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,{{args.baseline-hash}},demoapp-issuegen"
            canaryMetricScope: "argocd,{{args.canary-hash}},demoapp-issuegen"
            metricTemplateName: "PrometheusMetricTemplate" 
          - logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: "base"
            canaryLogScope: "can"
            logTemplateVersion: "v2.0"
        

